config/routes.rb
ProgrammingWebsite::Application.routes.draw do
  root 'pages#index'
  resources :pages
  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
   def new
   end
   
   def create
     @page = Page.new(params.require(:page).permit(:title, :text))
     @page.save

     redirect_to @page
   end

   def show
     @page = Page.find(params[:id])
   end

   def index
     @page = Page.all
   end

   def edit
     @page = Page.find(params[:id])
   end
   
   def update
     @page = Page.find(params[:id])
     
     if @page.update(params.require(:page).permit(:title, :text))
       redirect_to @page
     else
       render 'edit'
     end
   end

   def destroy
     @page = Page.find(params[:id])
     @page.destroy

     redirect_to pages_path
   end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>espace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/edit.html.erb
<%= stylesheet_link_tag "edit_page.css" %>

<body>
  <h1>Edit page</h1>

  <%= form_for :page, url: page_path(@page), method: :patch do |f| %>
    <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> Prohibited this article
        from being saved:</h2>
      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <p>
      <%=  f.label :title %><br>
      <%=  f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
</body>

app/views/pages/index.html.erb
<%= stylesheet_link_tag "index.css" %>

<head>
  <title>All Pages</title>
  <%= favicon_link_tag "/favicon.ico" %>
</head>

<body background='/assets/black_hole.jpg'>
  <div id="title">Visit to Outer Space</div>
  <div id="search">
  </div>

  <div id="purpose">
    <p>The purpose of this website is for me to gain a understanding of concepts related to space.  And for me to display the things that I'm looking up online in a fashionable way.</p>
  </div>

  <h1>The black hole of things</h1>

  <table align="center">
    <tr>
      <th>Link</th>
      <th>Title</th>
    </tr>

    <% @page.each_with_index do |page, index| %>
      <tr>
         <td><%= link_to "Page #" + (index+1).to_s, page_path(page) %></td>
         <td><%= link_to "\"" + page.title + "\"", page_path(page)  %></td>
         <td><%= link_to "Edit", edit_page_path(page) %></td>
         <td><%= link_to "Delete", page_path(page), method: :delete %></td>
      </tr>
    <% end %>
  </table>
</body>

app/views/pages/new.html.erb
<%=  stylesheet_link_tag "edit_page.css" %>
<h1>New Page</h1>

<%= form_for :page, url: pages_path  do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pages/show.html.erb
<%= stylesheet_link_tag "basic_page.css" %>

<div id="header">
  <b><%= @page.title %></b>
</div>

<br><br>

<%= raw @page.text %>

<div id="footer">
    <b><%= link_to "Main Page", controller: 'pages' %></b>
</div>